# Generated by Django 3.1.7 on 2021-05-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crop', '0002_auto_20210522_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_MarketPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('Yard_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='crop.crop')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, to='crop.category')),
            ],
        ),
    ]
