# Generated by Django 3.1.7 on 2021-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_crop',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_crop',
            name='payment_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
