# Generated by Django 3.1.7 on 2021-05-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agri',
            name='category',
        ),
        migrations.DeleteModel(
            name='Order_agri',
        ),
        migrations.DeleteModel(
            name='agri',
        ),
        migrations.DeleteModel(
            name='Category_agri',
        ),
    ]
