# Generated by Django 3.1.7 on 2021-05-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='category',
        ),
        migrations.DeleteModel(
            name='Order_machine',
        ),
        migrations.DeleteModel(
            name='Category_Machine',
        ),
        migrations.DeleteModel(
            name='machine',
        ),
    ]
